version: "2"
services:
  mysql:
    build: .
    image: "centos-mysql:6.9"
    container_name: ct-centos-mysql
    hostname: centos-mysql
    domainname: docker
    stop_signal: SIGTERM
    volumes:
      - data:/var/lib/mysql
    ports:
      - 3306:3306/tcp
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "testdb"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "1234"
volumes:
  data: {}